### PR TITLE
Release/v0.16.0

### PR DESCRIPTION
**Pull request by fivetran-catfritz**
## PR Overview
**This PR will address the following Issue/Feature:**
- #142 
- #147 

**This PR will result in the following new package version:**

- v0.16.0 breaking due to fundamental changes with the incremental logic for the end models.

**Please provide the finalized CHANGELOG entry which details the relevant changes included in this PR:**

## Breaking 

> Changes (Full Refresh Required)
> - Revised the incremental logic of the `netsuite2__transaction_details` model to use `transaction_lines` CTE as the primary driver instead of `transactions`. 
>   - This ensures all transaction lines are captured, including those synced after the parent transaction.
>   - This also aligns with `transaction_lines` serving as the base CTE in the model, onto which all other CTEs are left-joined.
>   - When the `balance_sheet_transaction_detail_columns` and `income_statement_transaction_detail_columns` variables are used in the `netsuite2__balance_sheet` and `netsuite2__income_statement` models, all transactions are now included during incremental runs. This ensures no transactions are missed, aligning with the changes made in the `netsuite2__transaction_details` model.
>   - We still recommend running `dbt --full-refresh` periodically to maintain data quality of the models.
> 
> ## Documentation
> - Updated dbt documentation definitions.

### Basic Validation
Please acknowledge that you have successfully performed the following commands locally:
- [x] dbt run –full-refresh && dbt test
- [x] dbt run (if incremental models are present) && dbt test

Before marking this PR as "ready for review" the following have been applied:
- [x] The appropriate issue has been linked, tagged, and properly assigned
- [x] All necessary documentation and version upgrades have been applied
- [x] docs were regenerated (unless this PR does not include any code or yml updates)
- [x] BuildKite integration tests are passing
- [x] Detailed validation steps have been provided below

### Detailed Validation
Please share any and all of your validation steps:

- See internal ticket for data results
- Consistency and integrity tests pass
  - Screenshot 2024-11-25 at 6 51 28 PM

### If you had to summarize this PR in an emoji, which would it be?
 
:dancer:

### CODE REVIEW

**Review by fivetran-joemarkiewicz — APPROVED** [review]
Overall these changes look good to me! Thanks for adding a new validation test to ensure integrity of the incremental model going forward. I just have a three small comments but nothing worth blocking an approval. Thanks!

**Review by fivetran-catfritz — COMMENTED** [review]
@fivetran-joemarkiewicz Thanks--made the updates!

**Comment by fivetran-reneeli** [comment]
Would we need to add an account join [here](https://github.com/fivetran/dbt_netsuite/blob/99a7aa566f6ad58ae9cf2fe77f5e64bd79090c44/models/netsuite2/netsuite2__income_statement.sql#L136-L138) as well?

**Comment by fivetran-catfritz** [comment]
> Would we need to add an account join [here](https://github.com/fivetran/dbt_netsuite/blob/99a7aa566f6ad58ae9cf2fe77f5e64bd79090c44/models/netsuite2/netsuite2__income_statement.sql#L136-L138) as well?

@fivetran-joemarkiewicz Could you take a look at this? @fivetran-reneeli asked a good question, but wondering if there was a reason.

**Review by fivetran-joemarkiewicz — APPROVED** [review]
LGTM! Thanks for making this update. @fivetran-catfritz as a final request please unlink Issue #128 from this PR so we don't auto close it after merging into main.

**Pull request merged**
